=pod

=head1 koha-illbackend-libris

Koha ILL Backend for Libris ILL (used in Sweden).

=head1 DOCUMENTATION

The official documentation of the Libris ILL API is available here: 
L<http://iller.libris.kb.se/librisfjarrlan/api/doc>

See the "docs" directory for more documentation on this ILL backend.

=head1 MAJOR CHANGES

=over 4

=item * 2019-11-21: Add support for empty form.

=item * 2019-11-26: Add support for multiple sigils. PLEASE NOTE: This changes
the way settings for the Libris backend are stored, from koha-conf.xml to a
separate YAML file. Please see the F<docs/config.pod> for details on the new config.

=item * 2020-05-13: patron_id_field is added as an optional config variable. The
default remains to use the user_id from the Libris data to look up patrons based
on cardnumber, but with this variable the backend can be told to use e.g. userid
or borrowernumber.

=back

=head1 NEW CONFIG VARIABLES

=over 4

=item * 2019-11-29: update_library_data, close_article_request_on_receive

=item * 2019-12-13: ill_callnumber

=item * 2020-05-13: patron_id_field (optional, default: cardnumber)

=item * 2020-09-30: ill_notforloan (optional, default: 0)

=back

=head1 AUTHOR

Magnus Enger <magnus@libriotech.no>

=cut
