=pod

=head1 CONFIGURATION

Some tips on how to configure the Libris ILL backend.

=head2 System preferences

=over 4

=item * B<ILLModule> = Enable

=back

=head2 koha-conf.xml

In this file you need to make sure you have set up a section called 
interlibrary_loans for the ILL stuff to work at all. Inside this section, you
need to add the following elements: 

=over 4

=item * B<libris_sigil> - The sigil used to identify the library in Libris.

=item * B<libris_key> - The API key for talking to the Libris API. Swedish
libraries can look this up when they are logged into Libris.

=item * B<unknown_patron> - borrowernumber for a dummy patron that can be used
if a connection to a real patron can not be established.

=item * B<unknown_biblio> - biblionumber of a dummy record that can be used
if a connection to a real biblio can not be established.

=back

Example: 

  <yazgfs>
    <config>
      <interlibrary_loans>
        ...
        <libris_sigil>xyz</libris_sigil>
        <libris_key>abc</libris_key>
        <unknown_patron>1</unknown_patron>
        <unknown_biblio>2</unknown_biblio>
        <ill_itemtype>FJARRLAN</ill_itemtype>
        <ill_branch>FJARRLAN</ill_branch>
        <ill_itemtype>FJARRLAN</ill_itemtype>
      </interlibrary_loans>
    <config>
  <yazgfs>

=head2 Notices

Add notices with the following codes under Tools > Notices and slips:

=over 4

=item * B<ILL_ANK_LAN> - For books and other media that are borrowed and returned.

=item * B<ILL_ANK_KOPIA> - For article copies that are not returned.

=back

The following settings should apply to all notices:

=over 4

=item * B<Library>: All libraries

=item * B<Koha module>: Circulation

=back

FIXME: Suggest content for the messages.

=head2 Cron jobs

See "perldoc cron/get_data_from_libris.pl" for details.

=cut
