=pod

=encoding utf8

=head1 LIBRIS ILL WORKFLOW

A description of the Libris ILL workflow and how it is reflcted in the "Libris" 
ILL backend.

=head2 Requests *to* our library from other libraries

=head3 Uteliggande | Remitterad => Läst

Retrieve "incoming" requests. These have a status of "Uteliggande" or
"Remitterad" and can be changed to "Läst".

=head3 Läst => Negativt svar

When a request is Läst, a response can be given to the requesting library.
These statuses are defined by Libris:

=over 4

=item 1 - Utlånad (On loan)

=item 2 - Förkommen (Missing)

=item 3 - Utlånas ej (Not for loan)

=item 4 - Finns ej (Does not exist) => [Negativt svar]

=item 5 - F n ej tillgänglig (Currently unavailable)

=item 6 - Ej anländ (Not arrived)

=item 7 - Reserverad för er (Reserved)

=item 8 - Övrigt (Other)

=item 9 - Levererad (Delivered)

=back

The status that will actually be returned by the API after given the responses
above are shown in square brackets.

=head2 Requests *from* our library to other libraries

=head2 NEW REQUESTS

New requests can come into the system a couple of different ways:

=over 4

=item * From the Libris API (processed by F<cron/get_data_from_libris.pm>)

=item * The empty form (processed by create() in F<Base.pm>)

=back

=cut
